# Generated by Django 3.0.5 on 2024-07-26 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPerguntaSaudeProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscalaSaudeProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaSaudeProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('ordem', models.IntegerField()),
                ('categoria_pergunta_saude_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.CategoriaPerguntaSaudeProjeto')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaudeProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('somatoria', models.IntegerField(default=0)),
                ('escala_saude_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.EscalaSaudeProjeto')),
                ('pergunta_saude_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.PerguntaSaudeProjeto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.Projeto')),
            ],
        ),
    ]
