# Generated by Django 3.0.5 on 2024-07-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_remove_saudeprojeto_somatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProsciProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaProsciProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('ordem', models.IntegerField()),
                ('categoria_pergunta_prosci_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='projeto.CategoriaProsciProjeto')),
            ],
        ),
        migrations.AlterField(
            model_name='perguntasaudeprojeto',
            name='categoria_pergunta_saude_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='projeto.CategoriaPerguntaSaudeProjeto'),
        ),
        migrations.AlterField(
            model_name='saudeprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saude', to='projeto.Projeto'),
        ),
        migrations.CreateModel(
            name='ProsciProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escala_prosci_projeto', models.IntegerField()),
                ('pergunta_prosci_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.PerguntaProsciProjeto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prosci', to='projeto.Projeto')),
            ],
        ),
    ]
