# Generated by Django 3.0.5 on 2024-07-27 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_auto_20240726_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSponsorPrimarioProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaSponsorPrimarioProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=1000)),
                ('ordem', models.IntegerField()),
                ('categoria_pergunta_sponsor_primario_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='projeto.CategoriaSponsorPrimarioProjeto')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorPrimarioProjeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('escala_sponsor_primario_projeto', models.IntegerField()),
                ('pergunta_sponsor_primario_projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projeto.PerguntaSponsorPrimarioProjeto')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_primario', to='projeto.Projeto')),
            ],
        ),
    ]
